# Generated by Django 6.0 on 2025-12-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('qualification', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
                ('audio', models.ImageField(upload_to='audio/')),
                ('video', models.ImageField(upload_to='video/')),
                ('document', models.ImageField(upload_to='document/')),
            ],
        ),
    ]
