# Generated by Django 6.0.1 on 2026-01-21 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_student_aadhar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aadhar',
            old_name='aadhar_number',
            new_name='aadhar_no',
        ),
        migrations.RenameField(
            model_name='aadhar',
            old_name='create_by',
            new_name='created_by',
        ),
        migrations.AlterField(
            model_name='student',
            name='aadhar',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.aadhar'),
        ),
    ]
