# Generated by Django 6.0.1 on 2026-01-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_aadhar_number_aadhar_aadhar_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadhar',
            name='aadhar_no',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
