# Generated by Django 6.0.1 on 2026-01-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_aadhar_aadhar_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadhar',
            name='created_by',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
